CREATE TABLE
  STKOUTBCK_OS (
    CLS varchar(16) COMMENT '出货方式',
    NUM varchar(14) COMMENT '单号',
    SETTLENO varchar COMMENT '结转期号',
    CLIENT varchar COMMENT '客户',
    BILLTO varchar COMMENT '结算单位',
    RECEIVER varchar COMMENT '收货单位',
    OCRDATE datetime COMMENT '发生日期',
    TOTAL decimal(24, 2) COMMENT '含税金额',
    TAX decimal(24, 2) COMMENT '税额',
    WRH varchar COMMENT '仓位',
    FILDATE datetime COMMENT '填单日期',
    FILLER varchar(90) COMMENT '填单人',
    STAT int COMMENT '状态',
    MODNUM varchar(14) COMMENT '修正单号',
    SLR varchar(90) COMMENT '销售员',
    NOTE varchar(1024) COMMENT '备注',
    RECCNT int COMMENT '记录数',
    SRC varchar COMMENT '来源单位',
    SNDTIME datetime COMMENT '上次发送时间',
    PRNTIME datetime COMMENT '上次打印时间',
    LSTUPDTIME datetime COMMENT '最近修改日期',
    IVCREG int COMMENT '发票登记标志',
    SENDCOUNT int COMMENT '发送次数',
    PAYMODE int COMMENT '付款方式',
    BCKCLS int COMMENT '退货原因',
    SRCNUM varchar(128) COMMENT '来源单号',
    ALCFEE decimal(24, 2) COMMENT '配送费',
    WHOLESALECLS int COMMENT '批发类型',
    PAYDATE datetime COMMENT '付款日期',
    CLIENTNUM varchar(30) COMMENT '对方单号',
    WHOLESALEDEPT varchar COMMENT '批发部门',
    ALCIVCREG int COMMENT '配销发票标志',
    BALREASON varchar(255) COMMENT '作废原因',
    SALESMAN varchar COMMENT '业务员',
    PAYTOTAL decimal(24, 2) COMMENT '已付金额',
    PAYREG int COMMENT '已付标志',
    CRTOTAL decimal(24, 2) COMMENT '门店售价金额',
    RTOTAL decimal(24, 2) COMMENT '出货售价金额',
    CPAYSCM varchar(32) COMMENT '结算方案',
    APPLYTOTAL decimal(24, 2) COMMENT '申请总金额',
    CARDNUM varchar(64) COMMENT '卡号',
    SAMT decimal(24, 2) COMMENT '门店去税发生金额',
    STAX decimal(24, 2) COMMENT '门店发生税额',
    SCAMT decimal(24, 2) COMMENT '门店去税成本额',
    SCTAX decimal(24, 2) COMMENT '门店成本税额',
    MANAGEFEE decimal(24, 2) COMMENT '管理费',
    BRANDFEE decimal(24, 2) COMMENT '品牌费',
    WMSNUM varchar(128) COMMENT '物流单号',
    UUID varchar(38) COMMENT 'JPOS主键',
    STKOUTNUM varchar(14) COMMENT '批发单号',
    SRCBILLCLS varchar(16) COMMENT '导入单据类型',
    SRCCLS varchar(20) COMMENT '来源类型',
    VIRCENTERGID int COMMENT '虚拟配送中心',
    LASTMODIFYOPER varchar(255) COMMENT '最后修改人',
    FLOWNO varchar(32) COMMENT '流水号',
    POSNO varchar(20) COMMENT 'POS机号',
    SRCDISCOUNT decimal(24, 4) COMMENT '原分销单折扣',
    DISCOUNT decimal(24, 4) COMMENT '折扣',
    CONTACTOR varchar(200) COMMENT '联系人',
    PHONENUMBER varchar(200) COMMENT '联系电话',
    WSCLS int COMMENT '分销类型',
    QTYTOTAL decimal(24, 4) COMMENT '数量合计',
    PRINTFLAG int COMMENT '是否打印',
    WORKID varchar(38) COMMENT '线上作业号',
    OLDBCK int COMMENT '是否旧货退货',
    DAYALC int COMMENT '是否日配退货',
    ORGGID varchar COMMENT '组织',
    SCANRECEIVER varchar(90) COMMENT '收货人',
    CLIENTPAYTYPE varchar(100) COMMENT '批发资金类型',
    CHECKER int COMMENT '复查人',
    CHECKNUM varchar(14) COMMENT '复查单号',
    OUTBILLNUMBER varchar(14) COMMENT '外部单号',
    WMSCOMPANY varchar(100) COMMENT '物流公司',
    WMSCPYNUM varchar(150) COMMENT '物流单号',
    QFSCMORDER int COMMENT '是否优货订单标记',
    INVXFNUM varchar(14) COMMENT '调拨单号',
    INVXFCLS varchar(16) COMMENT '调拨类型',
    TAXRATE decimal(24, 4) COMMENT '税率',
    BALUNIT varchar COMMENT '记账单位',
    ISVIRWRHWHOLE int COMMENT '虚拟仓分销',
    ISVIRTUALMODE int COMMENT '是否虚单',
    RCVDATE datetime COMMENT 'RF收货时间',
    CLIENTBALUNIT varchar COMMENT '退货方记账单位',
    DPSACCOUNT varchar COMMENT '加盟金账户',
    INVOICENO varchar(255) COMMENT '发票号',
    INVOICEURL varchar(255) COMMENT '开票地址',
    ISEMPTYMODE int COMMENT '是否空退模式',
    SENDTIME datetime COMMENT '发送时间',
    ISCONSUMABLE int COMMENT '耗材',
    PLATFORM varchar(16) COMMENT '平台',
    PLATFORMRTNNUM varchar(64) COMMENT '平台退货单号',
    BCKTYPE int COMMENT '类型',
    EXPRESS varchar(255) COMMENT '映射表达式',
    EXPRESSNUM varchar(64) COMMENT '运单号',
    PKGTOTAL decimal(24, 2) COMMENT '打包费',
    BCKLOSS int COMMENT '退货报损',
    CGTFLAG int COMMENT '代出标记',
    REFUNDFLAG int COMMENT '是否退货',
    WMSNOTE varchar(255) COMMENT '物流单据说明',
    ECRETURNNUMBER varchar(64) COMMENT '线上退货单号',
    SBCKREASON varchar(50) COMMENT '门店退货原因',
    SETTLEMENT int COMMENT '出账标识',
    DEP varchar(10) COMMENT '部门',
    SETTLEFREIGHT decimal(24, 2) COMMENT '结算运费',
    CARNUMBER varchar(32) COMMENT '车牌号',
    FREIGHTTOTAL decimal(24, 4) COMMENT '运费',
    SALEORDERNO varchar(64) COMMENT '商户订单号',
    PICKER varchar(90) COMMENT '拣货员',
    APPID varchar(64) COMMENT '开发者APPID',
    ISINVXFRTN int COMMENT '是否退货调拨',
    SETTLEMODE varchar(32) COMMENT '出账方式',
    COSTCENTER varchar(32) COMMENT '成本中心',
    NEEDACC int COMMENT '参与结算',
    ACCTOTAL decimal(24, 2) COMMENT '结算金额',
    ACCTAX decimal(24, 2) COMMENT '结算税额',
    PAYONDELIVERYSTATE int COMMENT '到付收款状态',
    PAYONDELIVERYDATE datetime COMMENT '到付收款时间',
    ERASETOTAL decimal(24, 2) COMMENT '抹零金额',
    WHOLESALESIGN int COMMENT '批发标记',
    INVUSESIGNTYPE varchar(10) COMMENT '领用类型',
    EXPRESSNAME varchar(200) COMMENT '承运商',
    RCVBALUNIT varchar COMMENT '收货方记账单位',
    SERVICEFEE decimal(24, 2) COMMENT '服务费',
    PRINTER varchar(64) COMMENT '条码打印人',
    OUTCLS varchar(38) COMMENT '外部单据类型',
    OUTNUM varchar(38) COMMENT '外部单号',
    TPLTOTAL decimal(24, 2) COMMENT '三方物流金额',
    TPLTAX decimal(24, 2) COMMENT '三方物流税额',
    EXGRATETYPE int COMMENT '汇率类型',
    EXCHANGERATE decimal(24, 4) COMMENT '汇率',
    STOREFILLER varchar COMMENT '门店填写人',
    STOREFILLTIME datetime COMMENT '门店填写时间',
    STORECHECKER int COMMENT '门店审批人',
    STORECHECKTIME datetime COMMENT '门店审批时间',
    POSRTNTIME datetime COMMENT 'Jopos端门店退货时间',
    SETTLEALONE int COMMENT '独立结算',
    STOREAREA varchar(20) COMMENT '储存区域',
    BUYERNO varchar(120) COMMENT '免税人编码',
    BUYERTAXFREE int COMMENT '是否免税',
    PM_RETURN_TIME datetime COMMENT '',
    BUSTYPE varchar(128) COMMENT '退货类型',
    BUSDATE datetime COMMENT '记账日期',
    DWMABUSDATE datetime COMMENT '日加权统计日期',
    LSTBCKDATE datetime COMMENT '最后退货日期',
    NOTIFYNUM varchar(32) COMMENT '通知单号',
    NOTIFYCLS varchar(16) COMMENT '通知类型',
    ASSISTANT varchar COMMENT '营业员',
    GUNUM varchar(64) COMMENT '全局单号',
    SRCGUNUM varchar(64),
    FCURTOTAL decimal(24, 4) COMMENT '外币金额',
    FCURTAX decimal(24, 4) COMMENT '外币税额',
    CLIENTINVCAT int COMMENT '门店库存分类',
    OUTSID varchar(38) COMMENT '外部系统',
    PRIMARY KEY (CLS, NUM)
  ) COMMENT = '出货退货单' Exists (
    Select
      1
    From
      Stkout t
    Where
      t.lstupdtime >= TRUNC (sysdate)
      and t.Num = stkoutdtl.Num
      and t.Cls = stkoutdtl.Cls
      and t.stat != 0
  )