SELECT 
A.SALE_COUNTRY
,ITEM_CODE,ITEM_NAME
,开售当天销量
, 开售前三天销量
,上机机器人数量
,国家机器人数量
,CASE WHEN 国家机器人数量=0 THEN 0 ELSE 上机机器人数量/国家机器人数量 END AS 新品上机率
FROM(
SELECT 
SALE_COUNTRY
,ITEM_CODE,ITEM_NAME
,SUM(开售当天销量) AS 开售当天销量
,SUM(开售前三天销量) AS 开售前三天销量
,SUM(上机机器人数量)  AS 上机机器人数量
FROM(
SELECT 
SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
,SUM(当天销售数量) AS 开售当天销量
,SUM(三天销售数量) AS 开售前三天销量
,0 AS 上机机器人数量
FROM(
SELECT  
A.SALE_COUNTRY
,A.ITEM_CODE
,A.ITEM_NAME
,A.总数量
,B.机器人销售数量
 ,A.TRAN_DATE
,A.CUSTITEM_PM_UP_DATE
,CASE WHEN A.TRAN_DATE=A.CUSTITEM_PM_UP_DATE THEN ISNULL(机器人销售数量,0) ELSE 0 END AS 当天销售数量
,CASE WHEN A.TRAN_DATE<=A.CUSTITEM_PM_UP_DATE + INTERVAL 3 DAY  THEN ISNULL(机器人销售数量,0) ELSE 0 END AS 三天销售数量
FROM
(SELECT 
SALE_COUNTRY

,ITEM_CODE
,ITEM_NAME
  ,TRAN_DATE

,CUSTITEM_PM_UP_DATE
 ,SUM(PRODUCT_COUNT)  AS 总数量
FROM(
SELECT
SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
,PRODUCT_COUNT
   ,TRAN_DATE
,B.CUSTITEM_PM_UP_DATE
    FROM 
    ns.dws_oversea_order_v2_detail A #商品明细销售表#
    LEFT JOIN  #69码匹配#
	(SELECT  
ITEMID,CUSTITEM_PM_UP_DATE
from 
	ns.DIM_OVERSEA_ITEM #商品上市表#) B
    ON  A.ITEM_CODE=B.ITEMID
	WHERE     CUSTRECORD_BI_BUDGET_ORDER_TYPE=1  AND   LEFT(TRAN_DATE,10)<=CURDATE() AND LEFT(TRAN_DATE,10)>=CURDATE()- INTERVAL 14 DAY  AND  SALE_COUNTRY IN (select 
	DISTINCT  SALE_COUNTRY
from 
	ns.dws_oversea_order_v2_detail
WHERE 
CUSTOMER_2ND_CAT_NAME IN ('ROBOshop' )
AND  CUSTRECORD_BI_BUDGET_ORDER_TYPE=1)
     AND IS_TARGET=1
     )AAA
GROUP  BY  
 SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
  ,TRAN_DATE
,CUSTITEM_PM_UP_DATE
)A
     LEFT JOIN  
     (SELECT 
SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
,TRAN_DATE

,CUSTITEM_PM_UP_DATE
      ,SUM(PRODUCT_COUNT) AS 机器人销售数量
FROM(
SELECT
SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
,PRODUCT_COUNT
 ,TRAN_DATE
,B.CUSTITEM_PM_UP_DATE
    FROM 
    ns.dws_oversea_order_v2_detail A
    LEFT JOIN  
	(SELECT  
ITEMID,CUSTITEM_PM_UP_DATE
from 
	ns.DIM_OVERSEA_ITEM) B
    ON  A.ITEM_CODE=B.ITEMID
	WHERE CUSTOMER_2ND_CAT_NAME IN ('ROBOshop' )  AND    CUSTRECORD_BI_BUDGET_ORDER_TYPE=1  AND   LEFT(TRAN_DATE,10)<=CURDATE() AND LEFT(TRAN_DATE,10)>=CURDATE()- INTERVAL 14 DAY
     AND IS_TARGET=1
     )AAA
     GROUP  BY  
      SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
,TRAN_DATE
,CUSTITEM_PM_UP_DATE
     )B
	 ON  A.SALE_COUNTRY=B.SALE_COUNTRY AND  A.ITEM_CODE=B.ITEM_CODE AND  A.TRAN_DATE=B.TRAN_DATE
     WHERE LEFT(A.CUSTITEM_PM_UP_DATE,10) <=CURDATE() AND  LEFT(A.CUSTITEM_PM_UP_DATE,10)>=CURDATE()- INTERVAL 14 DAY
      )AAA
  
     GROUP BY 
     SALE_COUNTRY
,ITEM_CODE
,ITEM_NAME
UNION  ALL 
SELECT 
SALE_COUNTRY
,ITEM_CODE,ITEM_NAME
,0 AS 开售当天销量
,0 AS 开售前三天销量
,COUNT(DISTINCT CUSTOMER_NAME) AS 上机机器人数量
 FROM(
SELECT 
SALE_COUNTRY
,ITEM_CODE,ITEM_NAME,CUSTOMER_NAME
,case when LEFT(TRAN_DATE,10)=LEFT(CUSTITEM_PM_UP_DATE,10) THEN  1 ELSE 0  END  AS 开售当天
FROM(
SELECT
A.*,B.CUSTITEM_PM_UP_DATE
    FROM 
    ns.dws_oversea_order_v2_detail A
    LEFT JOIN  
	(SELECT  
ITEMID,CUSTITEM_PM_UP_DATE
from 
	ns.DIM_OVERSEA_ITEM) B
    ON  A.ITEM_CODE=B.ITEMID
    )AA
    WHERE CUSTITEM_PM_UP_DATE IS NOT NULL 
    AND  CURDATE()- INTERVAL 30 DAY <= CAST(CUSTITEM_PM_UP_DATE AS DATE)
    AND LEFT(CUSTITEM_PM_UP_DATE,4)= LEFT(CURDATE(),4)
    AND CUSTOMER_2ND_CAT_NAME='ROBOshop'
)AAA
WHERE 开售当天=1
GROUP BY 
SALE_COUNTRY
,ITEM_CODE,ITEM_NAME
)AAA
GROUP BY 
SALE_COUNTRY
,ITEM_CODE,ITEM_NAME)A
LEFT JOIN  
(select 
	SALE_COUNTRY
 ,COUNT(DISTINCT CUSTOMER_NAME) AS 国家机器人数量
from 
	ns.dws_oversea_order_v2_detail
WHERE 
CUSTOMER_2ND_CAT_NAME IN ('ROBOshop' ) AND 
 TRAN_DATE  >=CURDATE() - INTERVAL 8 DAY
GROUP BY 
 SALE_COUNTRY
) B
ON  A.SALE_COUNTRY=B.SALE_COUNTRY   
WHERE  1=1 ${if(GUOJIA == '',"","and   A.SALE_COUNTRY in ('" + GUOJIA + "')")}