truncate table ns.zods_targetday;
replace into ns.zods_targetday
with t0 as (
  select 
    a.zcalday,
    b.entityid as CUSTOMER_CODE,
    b.id 
  from zcaldate a 
  left join ns.ZODS_CUSTOMER b 
  on 1=1 
  where a.zcalday>='20220101' 
    and a.zcalday<date_format(CURDATE + interval 1 day,'yyyyMMdd')
    and exists(
      select 
        date_format(CUSTRECORD_BI_BUDGET_MONTH,'yyyy') as zyear,
        CUSTRECORD_BI_BUDGET_CUSTOMER as CUSTOMER_ID 
      from ns.zods_budget as b 
      where date_format(a.zcalday,'yyyy')=date_format(CUSTRECORD_BI_BUDGET_MONTH,'yyyy') 
        and b.id=CUSTRECORD_BI_BUDGET_CUSTOMER
    )
), -- 日期,增加按预算表筛选
t01 as (
  select 
    b.id as customer_id,
    b.CUSTOMER_CODE,
    date_format(b.zcalday,'yyyy-MM-dd') as TRAN_DATE,
    nvl(a.MANAGMENT_PERFORMANCE_RMB,0) as MANAGMENT_PERFORMANCE_RMB,
    a.is_target
  from t0 as b 
  left join (
    select * 
    from ns.dm_oversea_customer_income_day 
    where is_target = 1
  ) as a 
  on a.CUSTOMER_CODE = b.CUSTOMER_CODE 
  and a.TRAN_DATE = b.zcalday
),-- 销售数据
t02 as (
  SELECT
    CUSTRECORD_BI_BUDGET_CUSTOMER,
    LEFT(CUSTRECORD_BI_BUDGET_MONTH, 7) AS budget_month,
    CUSTRECORD_BI_BUDGET_AMOUNT,
    b.id CUSTOMER_ID,
    SUBSIDIARY_NAME,
    COUNTRY_NAME SUBSIDIARY_COUNTRY,
    CUSTOMER_CONTINENT SUBSIDIARY_CONTINENT,
    b.ENTITYID as CUSTOMER_CODE,
    ALTNAME CUSTOMER_NAME,
    custentity_pm_store_seat CUSTOMER_CITY,
    COUNTRY_NAME CUSTOMER_COUNTRY,
    CATEGORYNAME CUSTOMER_CATEGORY,
    CATEGORYNAME2 CUSTOMER_2ND_CAT_NAME,
    CUSTOMER_3ND_CAT_NAME CUSTOMER_3ND_CAT_NAME,
    SUBSIDIARY_REGIONAL_SEGMENTATION,
    SUM(CUSTRECORD_BI_BUDGET_AMOUNT) OVER (PARTITION BY LEFT(CUSTRECORD_BI_BUDGET_MONTH, 4), CUSTRECORD_BI_BUDGET_CUSTOMER) AS YEAR_TARGET,
    SUM(CUSTRECORD_BI_BUDGET_AMOUNT) OVER (PARTITION BY LEFT(CUSTRECORD_BI_BUDGET_MONTH, 7), CUSTRECORD_BI_BUDGET_CUSTOMER ORDER BY CUSTRECORD_BI_BUDGET_MONTH) AS MONTH_TARGET,
    SUM(CUSTRECORD_BI_BUDGET_AMOUNT) OVER (PARTITION BY YEAR(CUSTRECORD_BI_BUDGET_MONTH), QUARTER(CUSTRECORD_BI_BUDGET_MONTH), CUSTRECORD_BI_BUDGET_CUSTOMER ORDER BY YEAR(CUSTRECORD_BI_BUDGET_MONTH), QUARTER(CUSTRECORD_BI_BUDGET_MONTH), CUSTRECORD_BI_BUDGET_CUSTOMER) AS QUARTER_TARGET
    FROM ns.ZODS_BUDGET as a 
    left join ns.ZODS_CUSTOMER as b 
    on a.CUSTRECORD_BI_BUDGET_CUSTOMER=b.ID
),-- 预算累加
t03 as (
  SELECT 
      b.id CUSTOMER_ID,
      SUBSIDIARY_NAME,
      COUNTRY_NAME SUBSIDIARY_COUNTRY,
      CUSTOMER_CONTINENT SUBSIDIARY_CONTINENT,
      CUSTOMER_CODE,
      ALTNAME CUSTOMER_NAME,
      custentity_pm_store_seat CUSTOMER_CITY,
      COUNTRY_NAME CUSTOMER_COUNTRY,
      CATEGORYNAME CUSTOMER_CATEGORY,
      CATEGORYNAME2 CUSTOMER_2ND_CAT_NAME,
      CUSTOMER_3ND_CAT_NAME CUSTOMER_3ND_CAT_NAME,
      a.TRAN_DATE AS DS_DATE,
      LEFT(a.TRAN_DATE, 7) AS tran_month,
      SUBSIDIARY_REGIONAL_SEGMENTATION,
      SUM(MANAGMENT_PERFORMANCE_RMB) OVER (PARTITION BY LEFT(TRAN_DATE, 4), CUSTOMER_CODE ORDER BY TRAN_DATE) AS YEAR_MANAGMENT_PERFORMANCE_RMB,
      SUM(MANAGMENT_PERFORMANCE_RMB) OVER (PARTITION BY LEFT(TRAN_DATE, 7), CUSTOMER_CODE ORDER BY TRAN_DATE) AS MONTH_MANAGMENT_PERFORMANCE_RMB,
      SUM(MANAGMENT_PERFORMANCE_RMB) OVER (PARTITION BY YEAR(TRAN_DATE), QUARTER(TRAN_DATE), CUSTOMER_CODE ORDER BY TRAN_DATE) AS QUARTER_MANAGMENT_PERFORMANCE_RMB
    FROM t01 a left join ns.ZODS_CUSTOMER b on a.CUSTOMER_CODE=b.ENTITYID
) -- 销售累加
SELECT 
  t03.CUSTOMER_ID,
  t03.SUBSIDIARY_NAME,
  t03.SUBSIDIARY_REGIONAL_SEGMENTATION,
  t03.SUBSIDIARY_CONTINENT,
  t03.CUSTOMER_CODE,
  t03.CUSTOMER_NAME,
  t03.CUSTOMER_CITY,
  t03.CUSTOMER_COUNTRY,
  t03.CUSTOMER_CATEGORY,
  t03.CUSTOMER_2ND_CAT_NAME,
  t03.CUSTOMER_3ND_CAT_NAME,
  DATE_FORMAT(t0.zcalday,'yyyy-MM-dd') as DS_DATE,
  t02.CUSTRECORD_BI_BUDGET_AMOUNT,
  coalesce(t03.YEAR_MANAGMENT_PERFORMANCE_RMB,0) YEAR_MANAGMENT_PERFORMANCE_RMB,
  coalesce(t03.MONTH_MANAGMENT_PERFORMANCE_RMB,0) MONTH_MANAGMENT_PERFORMANCE_RMB,
  coalesce(t03.QUARTER_MANAGMENT_PERFORMANCE_RMB,0) QUARTER_MANAGMENT_PERFORMANCE_RMB,
  t02.YEAR_TARGET,
  t02.MONTH_TARGET,
  t02.QUARTER_TARGET,
  DAYOFYEAR(t0.zcalday) / 
    CASE WHEN EXTRACT(YEAR FROM t0.zcalday) % 4 = 0 AND EXTRACT(YEAR FROM t0.zcalday) % 100 <> 0 OR EXTRACT(YEAR FROM t0.zcalday) % 400 = 0 THEN 366 ELSE 365 END AS YEAR_TIME_PROGRESS,
  DATEDIFF(t0.zcalday, MAKEDATE(YEAR(t0.zcalday), 1) + INTERVAL QUARTER(t0.zcalday) * 3 - 3 MONTH - INTERVAL 1 DAY) /
  DATEDIFF(LAST_DAY(MAKEDATE(EXTRACT(YEAR FROM t0.zcalday), 1) + INTERVAL QUARTER(t0.zcalday) * 3 - 1 MONTH), MAKEDATE(YEAR(t0.zcalday), 1) + INTERVAL QUARTER(t0.zcalday) * 3 - 3 MONTH - INTERVAL 1 DAY) AS QUARTER_TIME_PROGRESS,
  DAYOFMONTH(t0.zcalday) / DAYOFMONTH(LAST_DAY(t0.zcalday)) AS MONTH_TIME_PROGRESS,
  case when cnt=1 then 1 else 0 end as isopen
FROM 
  t0 left join t02 on left(DATE_FORMAT(t0.zcalday,"yyyy-MM-dd"),7) = t02.budget_month and t0.CUSTOMER_CODE = t02.CUSTOMER_CODE
  LEFT JOIN 
  t03 ON DATE_FORMAT(t0.zcalday,"yyyy-MM-dd") = t03.DS_DATE and t0.CUSTOMER_CODE = t03.CUSTOMER_CODE
  LEFT JOIN
  (select distinct date_format(CUSTRECORD_BI_BUDGET_MONTH,'yyyyMM') zmonth,
  CUSTRECORD_BI_BUDGET_CUSTOMER CUSTOMER_ID,1 cnt from ns.zods_budget) a on DATE_FORMAT(t0.zcalday,"yyyyMM")=a.zmonth and a.CUSTOMER_ID=t0.id;
